import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        media:"(prefers-color-scheme: dark)",
        url: "/logo_dark.png",
        href: "/logo_dark.png",
      },
      {
        media:"(prefers-color-scheme: light)",
        url: "/logo_light.png",
        href: "/logo_light.png",
      }
    ]
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen pt-16") }>
        {children}
      </body>
    </html>
  )
}
